language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
    - flags="--prefer-dist --no-dev"
    - composer install $flags

script: phpunit
